// User Types
export interface User {
  id: string;
  email: string;
  name: string;
  avatar?: string;
  role: "user" | "admin" | "super_admin";
  planId: string;
  createdAt: Date;
  updatedAt: Date;
}

// Subscription Types
export type PlanType = "free" | "pro" | "agency";

export interface Plan {
  id: PlanType;
  name: string;
  description: string;
  price: number;
  billingCycle: "monthly" | "annual";
  features: string[];
  limits: {
    proposalsPerMonth: number;
    clientLimit: number;
    projectLimit: number;
    automationRules: number;
    teamMembers: number;
  };
  popular?: boolean;
}

export interface Subscription {
  id: string;
  userId: string;
  planId: PlanType;
  status: "active" | "cancelled" | "expired";
  currentPeriodStart: Date;
  currentPeriodEnd: Date;
  cancelledAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

// Client Types
export interface Client {
  id: string;
  userId: string;
  name: string;
  email: string;
  platform: ("upwork" | "fiverr" | "linkedin" | "email" | "direct")[];
  budget?: number;
  paymentStatus: "paid" | "pending" | "overdue";
  communicationHistory: Message[];
  retainer?: RetainerClient;
  revenue: number;
  status: "active" | "inactive" | "lead";
  createdAt: Date;
  updatedAt: Date;
}

export interface RetainerClient {
  monthlyRate: number;
  startDate: Date;
  endDate?: Date;
  renewalDate: Date;
  isActive: boolean;
}

export interface Message {
  id: string;
  clientId: string;
  senderType: "user" | "client";
  content: string;
  timestamp: Date;
  read: boolean;
}

// Project Types
export interface Project {
  id: string;
  userId: string;
  clientId: string;
  name: string;
  description: string;
  status: "planning" | "in_progress" | "review" | "completed" | "cancelled";
  startDate: Date;
  deadline: Date;
  budget: number;
  paidAmount: number;
  deliverables: Deliverable[];
  taskIds: string[];
  priority: "low" | "medium" | "high" | "urgent";
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface Deliverable {
  id: string;
  name: string;
  description: string;
  status: "pending" | "in_progress" | "delivered" | "approved";
  dueDate: Date;
  files?: string[];
}

// Task Types
export interface Task {
  id: string;
  userId: string;
  projectId?: string;
  title: string;
  description: string;
  status: "todo" | "in_progress" | "in_review" | "done";
  priority: "low" | "medium" | "high" | "urgent";
  dueDate: Date;
  assignee?: string;
  labels: string[];
  subtasks?: Subtask[];
  attachments?: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Subtask {
  id: string;
  title: string;
  completed: boolean;
}

// Proposal Types
export interface Proposal {
  id: string;
  userId: string;
  clientId: string;
  title: string;
  content: string;
  status: "draft" | "sent" | "accepted" | "rejected";
  budget: number;
  timeline: string;
  platform: "upwork" | "fiverr" | "linkedin" | "email" | "direct";
  templateId?: string;
  responses?: ProposalResponse[];
  sentAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProposalResponse {
  id: string;
  clientReply: string;
  status: "sent" | "viewed" | "replied";
  timestamp: Date;
}

export interface ProposalTemplate {
  id: string;
  userId: string;
  name: string;
  content: string;
  category: "general" | "design" | "development" | "marketing" | "consulting";
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// Follow-up Types
export interface FollowUp {
  id: string;
  userId: string;
  clientId: string;
  proposalId?: string;
  type: "inquiry" | "revision" | "negotiation" | "scheduled_follow_up" | "payment_reminder";
  scheduledFor: Date;
  status: "pending" | "sent" | "completed";
  content?: string;
  autoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface FollowUpTemplate {
  id: string;
  userId: string;
  name: string;
  type: FollowUp["type"];
  content: string;
  toneStyle: "professional" | "friendly" | "persuasive" | "premium_agency";
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// Automation Types
export interface AutomationRule {
  id: string;
  userId: string;
  name: string;
  trigger: AutomationTrigger;
  actions: AutomationAction[];
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface AutomationTrigger {
  type: "proposal_sent" | "project_starts" | "payment_overdue" | "deadline_approaching" | "status_changed";
  conditions?: Record<string, any>;
}

export interface AutomationAction {
  type: "create_task" | "send_reminder" | "schedule_followup" | "send_email" | "update_status";
  payload: Record<string, any>;
}

// Report Types
export interface Report {
  id: string;
  userId: string;
  type: "weekly" | "monthly" | "project_delivery" | "performance" | "revenue";
  period: {
    startDate: Date;
    endDate: Date;
  };
  data: ReportData;
  generatedAt: Date;
  exportedAt?: Date;
}

export interface ReportData {
  proposalsSent: number;
  projectsCompleted: number;
  totalRevenue: number;
  clientsOnboarded: number;
  tasksCompleted: number;
  averageProjectDuration: number;
  clientSatisfaction?: number;
  topClients?: Array<{ name: string; revenue: number }>;
  projectBreakdown?: Array<{ name: string; status: string; progress: number }>;
}

// Invoice Types
export interface Invoice {
  id: string;
  userId: string;
  clientId: string;
  projectId?: string;
  amount: number;
  status: "draft" | "sent" | "viewed" | "paid" | "overdue";
  dueDate: Date;
  issuedDate: Date;
  paidDate?: Date;
  items: InvoiceItem[];
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface InvoiceItem {
  id: string;
  description: string;
  quantity: number;
  rate: number;
  amount: number;
}

// Calendar Event Types
export interface CalendarEvent {
  id: string;
  userId: string;
  title: string;
  description?: string;
  startTime: Date;
  endTime: Date;
  type: "deadline" | "meeting" | "followup" | "delivery" | "payment_due" | "other";
  relatedEntityId?: string;
  relatedEntityType?: "project" | "client" | "task" | "invoice";
  reminders: Date[];
  color?: string;
}

// Dashboard Widgets Types
export interface DashboardWidget {
  id: string;
  userId: string;
  type:
    | "revenue_overview"
    | "active_projects"
    | "recent_proposals"
    | "pending_followups"
    | "upcoming_deadlines"
    | "client_metrics"
    | "task_status"
    | "calendar";
  position: { x: number; y: number };
  size: { width: number; height: number };
  settings?: Record<string, any>;
}

// API Request/Response Types
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface PaginatedResponse<T> {
  success: boolean;
  data: T[];
  pagination: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
  error?: string;
}
